config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about" => "pages#about" # Creates about_path
  get "blog" => "pages#blog"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Blog", blog_path %></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
  <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>
		<%= yield %>
	</div>	

</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our One Month Rails Pinteresting App.</p>

app/views/pages/blog.html.erb
<h1>Pinteresting Blog Page</h1>
	
		<center>This page will include updates and progress on my 
		<a href="http://onemonthrails.com">One Month Rails </a>class</center>

	<div class="jumbotron">
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="https://img0.etsystatic.com/058/0/7081676/il_570xN.744945130_lvs9.jpg" alt="...">
      <div class="caption">
        <h3>T3 Designs Co. Invite</h3>
        <p>Click to go to view on our Website or Etsy Store</p>
        <p><a href="http://www.t3designs.com" class="btn btn-primary" role="button">Website</a> <a href="https://www.etsy.com/shop/T3DesignsCo" class="btn btn-default" role="button">Etsy</a></p>
      </div>
    </div>
  </div>
</div>
	</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
	<p>
		<%= link_to "Sign up", "#", class: "btn btn-default btn-lg"%>
		<%= link_to "Login", "#", class: "btn btn-primary btn-lg"%>
	</p>
</div>